/*
 * Stash
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.7.0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.stash.client.models;

import java.util.Objects;
import com.appscode.stash.client.models.V1alpha1RestoreStats;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1RecoveryStatus
 */

public class V1alpha1RecoveryStatus {
  @SerializedName("phase")
  private String phase = null;

  @SerializedName("stats")
  private List<V1alpha1RestoreStats> stats = null;

  public V1alpha1RecoveryStatus phase(String phase) {
    this.phase = phase;
    return this;
  }

   /**
   * Get phase
   * @return phase
  **/
  @ApiModelProperty(value = "")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }

  public V1alpha1RecoveryStatus stats(List<V1alpha1RestoreStats> stats) {
    this.stats = stats;
    return this;
  }

  public V1alpha1RecoveryStatus addStatsItem(V1alpha1RestoreStats statsItem) {
    if (this.stats == null) {
      this.stats = new ArrayList<V1alpha1RestoreStats>();
    }
    this.stats.add(statsItem);
    return this;
  }

   /**
   * Get stats
   * @return stats
  **/
  @ApiModelProperty(value = "")
  public List<V1alpha1RestoreStats> getStats() {
    return stats;
  }

  public void setStats(List<V1alpha1RestoreStats> stats) {
    this.stats = stats;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RecoveryStatus v1alpha1RecoveryStatus = (V1alpha1RecoveryStatus) o;
    return Objects.equals(this.phase, v1alpha1RecoveryStatus.phase) &&
        Objects.equals(this.stats, v1alpha1RecoveryStatus.stats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phase, stats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RecoveryStatus {\n");
    
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

