/*
 * Stash
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.7.0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.stash.client.models;

import java.util.Objects;
import com.appscode.stash.client.models.V1alpha1Backend;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1RepositorySpec
 */

public class V1alpha1RepositorySpec {
  @SerializedName("backend")
  private V1alpha1Backend backend = null;

  @SerializedName("wipeOut")
  private Boolean wipeOut = null;

  public V1alpha1RepositorySpec backend(V1alpha1Backend backend) {
    this.backend = backend;
    return this;
  }

   /**
   * Get backend
   * @return backend
  **/
  @ApiModelProperty(value = "")
  public V1alpha1Backend getBackend() {
    return backend;
  }

  public void setBackend(V1alpha1Backend backend) {
    this.backend = backend;
  }

  public V1alpha1RepositorySpec wipeOut(Boolean wipeOut) {
    this.wipeOut = wipeOut;
    return this;
  }

   /**
   * If true, delete respective restic repository
   * @return wipeOut
  **/
  @ApiModelProperty(value = "If true, delete respective restic repository")
  public Boolean isWipeOut() {
    return wipeOut;
  }

  public void setWipeOut(Boolean wipeOut) {
    this.wipeOut = wipeOut;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RepositorySpec v1alpha1RepositorySpec = (V1alpha1RepositorySpec) o;
    return Objects.equals(this.backend, v1alpha1RepositorySpec.backend) &&
        Objects.equals(this.wipeOut, v1alpha1RepositorySpec.wipeOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backend, wipeOut);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RepositorySpec {\n");
    
    sb.append("    backend: ").append(toIndentedString(backend)).append("\n");
    sb.append("    wipeOut: ").append(toIndentedString(wipeOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

