/*
 * Stash
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.7.0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.stash.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * V1alpha1RepositoryStatus
 */

public class V1alpha1RepositoryStatus {
  @SerializedName("backupCount")
  private Long backupCount = null;

  @SerializedName("firstBackupTime")
  private DateTime firstBackupTime = null;

  @SerializedName("lastBackupDuration")
  private String lastBackupDuration = null;

  @SerializedName("lastBackupTime")
  private DateTime lastBackupTime = null;

  @SerializedName("lastSuccessfulBackupTime")
  private DateTime lastSuccessfulBackupTime = null;

  public V1alpha1RepositoryStatus backupCount(Long backupCount) {
    this.backupCount = backupCount;
    return this;
  }

   /**
   * Get backupCount
   * @return backupCount
  **/
  @ApiModelProperty(value = "")
  public Long getBackupCount() {
    return backupCount;
  }

  public void setBackupCount(Long backupCount) {
    this.backupCount = backupCount;
  }

  public V1alpha1RepositoryStatus firstBackupTime(DateTime firstBackupTime) {
    this.firstBackupTime = firstBackupTime;
    return this;
  }

   /**
   * Get firstBackupTime
   * @return firstBackupTime
  **/
  @ApiModelProperty(value = "")
  public DateTime getFirstBackupTime() {
    return firstBackupTime;
  }

  public void setFirstBackupTime(DateTime firstBackupTime) {
    this.firstBackupTime = firstBackupTime;
  }

  public V1alpha1RepositoryStatus lastBackupDuration(String lastBackupDuration) {
    this.lastBackupDuration = lastBackupDuration;
    return this;
  }

   /**
   * Get lastBackupDuration
   * @return lastBackupDuration
  **/
  @ApiModelProperty(value = "")
  public String getLastBackupDuration() {
    return lastBackupDuration;
  }

  public void setLastBackupDuration(String lastBackupDuration) {
    this.lastBackupDuration = lastBackupDuration;
  }

  public V1alpha1RepositoryStatus lastBackupTime(DateTime lastBackupTime) {
    this.lastBackupTime = lastBackupTime;
    return this;
  }

   /**
   * Get lastBackupTime
   * @return lastBackupTime
  **/
  @ApiModelProperty(value = "")
  public DateTime getLastBackupTime() {
    return lastBackupTime;
  }

  public void setLastBackupTime(DateTime lastBackupTime) {
    this.lastBackupTime = lastBackupTime;
  }

  public V1alpha1RepositoryStatus lastSuccessfulBackupTime(DateTime lastSuccessfulBackupTime) {
    this.lastSuccessfulBackupTime = lastSuccessfulBackupTime;
    return this;
  }

   /**
   * Get lastSuccessfulBackupTime
   * @return lastSuccessfulBackupTime
  **/
  @ApiModelProperty(value = "")
  public DateTime getLastSuccessfulBackupTime() {
    return lastSuccessfulBackupTime;
  }

  public void setLastSuccessfulBackupTime(DateTime lastSuccessfulBackupTime) {
    this.lastSuccessfulBackupTime = lastSuccessfulBackupTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RepositoryStatus v1alpha1RepositoryStatus = (V1alpha1RepositoryStatus) o;
    return Objects.equals(this.backupCount, v1alpha1RepositoryStatus.backupCount) &&
        Objects.equals(this.firstBackupTime, v1alpha1RepositoryStatus.firstBackupTime) &&
        Objects.equals(this.lastBackupDuration, v1alpha1RepositoryStatus.lastBackupDuration) &&
        Objects.equals(this.lastBackupTime, v1alpha1RepositoryStatus.lastBackupTime) &&
        Objects.equals(this.lastSuccessfulBackupTime, v1alpha1RepositoryStatus.lastSuccessfulBackupTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backupCount, firstBackupTime, lastBackupDuration, lastBackupTime, lastSuccessfulBackupTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RepositoryStatus {\n");
    
    sb.append("    backupCount: ").append(toIndentedString(backupCount)).append("\n");
    sb.append("    firstBackupTime: ").append(toIndentedString(firstBackupTime)).append("\n");
    sb.append("    lastBackupDuration: ").append(toIndentedString(lastBackupDuration)).append("\n");
    sb.append("    lastBackupTime: ").append(toIndentedString(lastBackupTime)).append("\n");
    sb.append("    lastSuccessfulBackupTime: ").append(toIndentedString(lastSuccessfulBackupTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

