/*
 * Stash
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.7.0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.stash.client.models;

import java.util.Objects;
import com.appscode.stash.client.models.V1alpha1LocalSpec;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.models.V1LocalObjectReference;
import io.kubernetes.client.models.V1ObjectReference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1RecoverySpec
 */

public class V1alpha1RecoverySpec {
  @SerializedName("imagePullSecrets")
  private List<V1LocalObjectReference> imagePullSecrets = null;

  @SerializedName("paths")
  private List<String> paths = null;

  @SerializedName("recoveredVolumes")
  private List<V1alpha1LocalSpec> recoveredVolumes = null;

  @SerializedName("repository")
  private V1ObjectReference repository = null;

  @SerializedName("snapshot")
  private String snapshot = null;

  public V1alpha1RecoverySpec imagePullSecrets(List<V1LocalObjectReference> imagePullSecrets) {
    this.imagePullSecrets = imagePullSecrets;
    return this;
  }

  public V1alpha1RecoverySpec addImagePullSecretsItem(V1LocalObjectReference imagePullSecretsItem) {
    if (this.imagePullSecrets == null) {
      this.imagePullSecrets = new ArrayList<V1LocalObjectReference>();
    }
    this.imagePullSecrets.add(imagePullSecretsItem);
    return this;
  }

   /**
   * Get imagePullSecrets
   * @return imagePullSecrets
  **/
  @ApiModelProperty(value = "")
  public List<V1LocalObjectReference> getImagePullSecrets() {
    return imagePullSecrets;
  }

  public void setImagePullSecrets(List<V1LocalObjectReference> imagePullSecrets) {
    this.imagePullSecrets = imagePullSecrets;
  }

  public V1alpha1RecoverySpec paths(List<String> paths) {
    this.paths = paths;
    return this;
  }

  public V1alpha1RecoverySpec addPathsItem(String pathsItem) {
    if (this.paths == null) {
      this.paths = new ArrayList<String>();
    }
    this.paths.add(pathsItem);
    return this;
  }

   /**
   * Get paths
   * @return paths
  **/
  @ApiModelProperty(value = "")
  public List<String> getPaths() {
    return paths;
  }

  public void setPaths(List<String> paths) {
    this.paths = paths;
  }

  public V1alpha1RecoverySpec recoveredVolumes(List<V1alpha1LocalSpec> recoveredVolumes) {
    this.recoveredVolumes = recoveredVolumes;
    return this;
  }

  public V1alpha1RecoverySpec addRecoveredVolumesItem(V1alpha1LocalSpec recoveredVolumesItem) {
    if (this.recoveredVolumes == null) {
      this.recoveredVolumes = new ArrayList<V1alpha1LocalSpec>();
    }
    this.recoveredVolumes.add(recoveredVolumesItem);
    return this;
  }

   /**
   * Get recoveredVolumes
   * @return recoveredVolumes
  **/
  @ApiModelProperty(value = "")
  public List<V1alpha1LocalSpec> getRecoveredVolumes() {
    return recoveredVolumes;
  }

  public void setRecoveredVolumes(List<V1alpha1LocalSpec> recoveredVolumes) {
    this.recoveredVolumes = recoveredVolumes;
  }

  public V1alpha1RecoverySpec repository(V1ObjectReference repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  @ApiModelProperty(required = true, value = "")
  public V1ObjectReference getRepository() {
    return repository;
  }

  public void setRepository(V1ObjectReference repository) {
    this.repository = repository;
  }

  public V1alpha1RecoverySpec snapshot(String snapshot) {
    this.snapshot = snapshot;
    return this;
  }

   /**
   * Snapshot to recover. Default is latest snapshot.
   * @return snapshot
  **/
  @ApiModelProperty(value = "Snapshot to recover. Default is latest snapshot.")
  public String getSnapshot() {
    return snapshot;
  }

  public void setSnapshot(String snapshot) {
    this.snapshot = snapshot;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RecoverySpec v1alpha1RecoverySpec = (V1alpha1RecoverySpec) o;
    return Objects.equals(this.imagePullSecrets, v1alpha1RecoverySpec.imagePullSecrets) &&
        Objects.equals(this.paths, v1alpha1RecoverySpec.paths) &&
        Objects.equals(this.recoveredVolumes, v1alpha1RecoverySpec.recoveredVolumes) &&
        Objects.equals(this.repository, v1alpha1RecoverySpec.repository) &&
        Objects.equals(this.snapshot, v1alpha1RecoverySpec.snapshot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imagePullSecrets, paths, recoveredVolumes, repository, snapshot);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RecoverySpec {\n");
    
    sb.append("    imagePullSecrets: ").append(toIndentedString(imagePullSecrets)).append("\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    recoveredVolumes: ").append(toIndentedString(recoveredVolumes)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    snapshot: ").append(toIndentedString(snapshot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

